name: build mkdocs
on: [push]
jobs:
  build-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
            REQUIREMENTS: requirements.txt